# Day 3 : Variables, Functions and Tables

In this notebook we will:
    
- Review how Python does arithmetic
- Learn how to use variable names
- Learn **WHY** we use **descriptive variable names**
- Review a few of Python's built-in functions and learn a few more
- Learn more **table** basics

Over time, we'll learn more Python functions as we need them. Tables are a big topic, and we'll come back to them repeatedly throughout the course.

The code in the cell below imports the various toolkits we will use to make our commands quite simple. **Just run it without changing anything.**

In [3]:
from datascience import *
import numpy as np
import scipy.stats as stats

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Scientific Computing

When we need for Python to behave as a scientific calculator, we must remember a couple of things:

- Exponentiate with 2**3 and not 2^3
- Inset mixed numbers like $2\frac{1}{3}$ as (2+1/3).

In [4]:
2 + 3 * 9

29

In [5]:
(2 + 3) * 9

45

#### Practice question: evaluate two to the power of four, e.g. 2 * 2 * 2 * 2

In [6]:
# 
two_to_fourth = ...

#### Python includes a **string** data type for text

In [7]:
"hello"

'hello'

## Variables and Naming Them

Variables work like they do in basic algebra excpet that the cell<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">x = 7</span></center></br>

tells Python to create the variable named $x$ and store the value of $7$ in it.

As seen below, we can use the double-equal-sign to check a value:<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">10 == x</span></center></br>asks Python to verify that the value of $10$ is stored the variable $x$.

In [8]:
a = 4

In [9]:
7 == a

False

In [10]:
a

4

In [11]:
b = 9

In [12]:
b

9

In [13]:
a * 3

12

In [14]:
3 * a

12

In [15]:
total = a + b

In [16]:
total

13

In [17]:
a = 10

In [18]:
total

13

### Interesting!!

Note that value stored in **total** has *not* been updated despite a new value for $a$ being created.

Let's redefine **total** below to include the updated value for $a$.

In [19]:
total = a + b

In [20]:
total

19

### String Variables

We can store strings (e.g. text) in a variable, too.

In [21]:
word = 'total'
word

'total'

### Descriptive Variable Names

Names that describe what the variable is are helpful.  In the future, returning to a notebook with variable names like **a** and **b** instead of **hours_per_week** and **hours_per_year** will require more time to understand the code because you'll be struggling to remember what **a** and **b** stand for. 

#### Work Hours in a Standard Work Week

In [22]:
hours_per_week = 40
weeks_per_year = 52

#### Work Hours in a Year

In [23]:
hours_per_year = ...

In [24]:
# Minimum wage in California (2022) for businesses w/26 or more employees
ca_hourly_minimum_wage = 15.00

#### Wages per Week and Wages per Year

In [25]:
weekly_wages = ...

In [26]:
yearly_wages = ...

## Functions

A helpful feature of Python's functions is that we can evaluate an expression inside the parenthesis of the function call as in the following:<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">abs(4-9)</span></center></br>which will evalute to $5$.

In [27]:
max(15, 27*2, 50)

54

In [28]:
min(15, 27*2, 50)

15

In [29]:
abs(-5) , abs(1 - 3)

(5, 2)

#### We can use **variables** as input for our functions in Python.

We can also enter multiple values in the functions **max** and **min**.

In [30]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

In [31]:
min(14, 15)

14

#### Python's **round()** functions allows for a second input to identify to which digit we're rounding.

In [32]:
round(123.456)

123

#### Practice Question: round the value $123345678.456789$ to the 4th decimal place.

In [33]:
rounded = ...

### Let's create an example array to use with these functions

The data set represents daily high temperatures in Dahlonega, GA, for the month of November. Answer the practice questions below the data set.

In [34]:
N = make_array(67, 65, 66, 63, 60, 62, 64, 68, 71, 69, 65, 62, 59, 58, 61,
               63, 66, 62, 59, 57, 55, 58, 60, 63, 62, 58, 56, 54, 57, 59)

#### What is the maximum high temperature?

In [54]:
ga_nov_max = ...

#### What is the minimum high temperature?

In [55]:
ga_nov_min = ...

#### What is the range in daily high temperatures in November?

In [56]:
ga_nov_range = ...

#### How many data points are in the array N?

In [57]:
sample_size = ...

## Tables

We will import the **cones** table to help us learn three basic table methods:

- **.sort**
- **.select**
- **.drop**

In [58]:
cones = Table.read_table('cones.csv')

#### Note that Python has done the importing but shows nothing we can see visually.

We have to enter the table name by itself to see its contents.

In [59]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### The **.show** Method

Recall the example in the previous notebook: <center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.show()</span></center></br>displayed a table. Inside the parenthesis, we indicate how many rows we wish to see

In [60]:
cones.show(3)

### The **.select** Method

We use the<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.select()</span></center></br>method to display a single column (or columns) of data. Note that we use the column titles in quotations marks, but we can also use column numbers.

Also, the new display will rorder the columns depending upon which order we enter the titles (or numbers).

In [61]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [62]:
cones.select('Price', 'Flavor')

Price | Flavor
3.55  | strawberry
4.75  | chocolate
5.25  | chocolate
5.25  | strawberry
5.25  | chocolate
4.75  | bubblegum

In [63]:
cones.select(0,1)

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

#### Practice question: display cones table with only columns Flavor and Price.

In [66]:
cones_flavor_price = ...

#### **The original table has NOT been changed**

The table methods<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.select</span> and <span style="color:darkblue; font-weight:bold; font-size:1.2em">.show</span></center></br> do not alter the original table. They only change how the table displays as shown in the cell below.

In [67]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### The **.drop** Method

The<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.drop()</span></center></br>method is similar to **.select** but drops a column and displays the other original columns.

In [68]:
cones.drop('Color')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [69]:
# Practice question:
cones_without_price = ...
cones_without_price

Ellipsis

### The **.sort** Method

Often, to quickly find a maximum or minimum value, we can sort a column using the<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">.sort</span></center></br>method.

The **.sort()** sorts in ascending order (1,2,3,... or a,b,c,...) based upon the column title given inside the paranthesis. We have a second input called<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">descending = True</span></center></br>which we can add to reverse the sort.

In [70]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [71]:
cones.sort('Price', descending = True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

#### **Shortcut**

We can shorten the second input to <center><span style="color:darkblue; font-weight:bold; font-size:1.2em">True</span></center></br> which works as Python knows that only one option exists for the **.sort** method.

In [72]:
cones.sort('Price', True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

#### Practice question: sort the cones table based upon the Flavor column.

## More Interesting Tables

We can import much bigger and more sophisticated data sets using the<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">Table.read_table()</span></center></br>function as shown below.

In [76]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

# Searching Tables: the **.where** method



To find and display the buildings in the table that are located in Los Angeles, we can use:<center><span style="color:darkblue; font-weight:bold; font-size:1.2em">skyscrapers.where('city','Los Angeles')</span></center></br>
Notice with **.where** we have two inputs:
1. Column title indicating **where** to search, and
2. Exact text to search for.

We can also search for values instead of text, and we have **predicates** that are helpers for performing common searches.

In [78]:
# Performing the example shown above
skyscrapers.where('city','Los Angeles')

name                  | material | city        | height | completed
U.S. Bank Tower       | steel    | Los Angeles | 310.29 | 1990
Aon Center            | steel    | Los Angeles | 261.52 | 1974
Two California Plaza  | steel    | Los Angeles | 228.6  | 1992
Gas Company Tower     | steel    | Los Angeles | 228.3  | 1991
Bank of America Plaza | steel    | Los Angeles | 224.03 | 1975
777 Tower             | steel    | Los Angeles | 221    | 1991
Wells Fargo Tower     | steel    | Los Angeles | 220.37 | 1983
Figueroa at Wilshire  | steel    | Los Angeles | 218.54 | 1989
City National Tower   | steel    | Los Angeles | 213.06 | 1971
Paul Hastings Tower   | steel    | Los Angeles | 213.06 | 1971
... (1 rows omitted)

### Practice Question: Is the Empire State Building in the table?

**Hint:** use the 'name' column.

In [84]:
empire_state = ...

### Practice Question: What are the oldest New York City skyscrapers in this table?

**Hint:** use a search and a sort.

In [85]:
oldest = ...

### Practice Question: What are the newest New York City skyscrapers in this table?

**Hint:** how do we reverse the sort order?

In [86]:
newest = ...

### Practice Question: Display the skyscrapers in both LA and NYC, but no others.

**Hint:** we will use the **are.contained_in()** predicate to assist our **.where** search. This function will search inside a string for the cities we specify:
- New York City
- Los Angeles

In [92]:
la_nyc = ...

### Practice Question: Find the buildings in the table that were built in the 1970's.

Hint: use the predicate **are.between()** to assist the **.where** method.

In [93]:
seventies = ...

### Practice Question: Find the buildings in the table that are 300 meters tall, or taller.

Hint: use the predicate **are.above()** with the **.where** method.

In [95]:
above_300 = ...

### Practice Question: Display the skyscrapers that are not in either LA or NYC.

**Hint:** use the **are.not_contained_in()** predicate with our **.where** search.

In [96]:
notin_la_nyc = ...

### Practice Question: Find and display all the Atlanta skyscrapers.

In [99]:
atl = ...

### Practice Question: How many Atlanta skyscrapers have "Peachtree" in their titles?

In [98]:
num_peaches = ...